In [7]:
import numpy as np 
import scipy 

R = np.array([
    [1, 0, 0, 1, 3],
    [2, 0, 3, 1, 1],
    [1, 2, 0, 5, 0],
    [1, 0, 0, 4, 4],
    [2, 1, 5, 4, 0],
    [5, 1, 5, 4, 0],
    [0, 0, 0, 1, 0],
])

rating_matrix = scipy.sparse.csr_matrix(R)

In [8]:
from implicit.evaluation import  *
from implicit.als import AlternatingLeastSquares as ALS
from implicit.bpr import BayesianPersonalizedRanking as BPR

als_model = ALS(factors=3, regularization=0.01, iterations = 100)
als_model.fit(rating_matrix.T)

In [14]:
als_model.user_factors

array([[-0.43390596,  0.7792046 ,  0.72156245],
       [ 0.25987417,  1.585035  , -0.07761745],
       [ 0.5883245 ,  0.67921823,  1.4624232 ],
       [-0.44013542,  0.76680833,  0.68539524],
       [ 1.2584542 ,  1.5149189 ,  0.70578897],
       [ 1.2584835 ,  1.5153128 ,  0.7062366 ],
       [-0.01211063,  0.24986167,  0.54429907]], dtype=float32)

In [13]:
als_model.item_factors

array([[-0.2741828 ,  0.70229995,  0.39969537],
       [ 0.6381009 , -0.07443979,  0.44144744],
       [ 0.3407201 ,  0.5544682 , -0.38120595],
       [-0.32385796,  0.68887347,  0.51305306],
       [-0.9246371 ,  0.78346837, -0.02537217]], dtype=float32)

In [19]:
np.dot(als_model.user_factors, als_model.item_factors.T) * 5

array([[ 4.7730503 , -0.08173858,  0.04569907,  5.237486  ,  4.966901  ],
       [ 5.054468  ,  0.06786128,  4.9849205 ,  4.8395214 ,  5.017524  ],
       [ 4.5011516 ,  4.8521624 ,  0.09787245,  5.1383123 , -0.24472743],
       [ 4.6657815 , -0.17682949,  0.06965568,  5.1120973 ,  4.9517283 ],
       [ 5.0049076 ,  5.009096  ,  4.99852   ,  4.990671  ,  0.02685123],
       [ 5.0071454 ,  5.0100317 ,  4.998809  ,  4.993129  ,  0.0282017 ],
       [ 1.9817609 ,  1.0697598 , -0.3653801 ,  2.2764974 ,  0.96573305]],
      dtype=float32)